config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  # , only: []
  resources :clients, except: :destroy
  resources :reservations, only: [:index, :create, :update] do
    member do
      put "custumDelete"
      put "revival"
      # collectionにして,jsでURLのidを抜いてdataでidを送っても可
      get "takeReservation"
    end
  end
  resources :sales
  resources :sales_drinks, only: :destroy
  # シフト機能実装後用
  # resources :myinfos, only: :index
  devise_for :members, skip: :all
  devise_scope :member do
    get '/members/sign_in' => 'devise/sessions#new', as: :new_member_session
    post '/members/sign_in' => 'devise/sessions#create', as: :member_session
    delete '/members/sign_out' => 'devise/sessions#destroy', as: :destroy_member_session
    get '/members/sign_up' => 'devise/registrations#new', as: :new_member_registration
    post '/members' => 'devise/registrations#create', as: :member_registration
  end
  resources :members, only: [:index, :edit, :update] do
    member do
      put "custumDelete"
    end
    collection do
      get "wait"
    end
  end
  root 'reservations#index'
  # シフト機能実装後用
  # root 'myinfos#index'
end

app/models/drink.rb
class Drink < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :category, presence: true

  enum category: {ビール:0,シャンパーニュ:1,赤ワイン:2,白ワイン:3,焼酎:4,ウイスキー:5,ソフトドリンク:6,その他:7}
  
  has_many :sales, through: :sales_drinks
  has_many :sales_drinds
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :except_1member, except: [:index, :show]
  before_action :set_drink, except: [:new, :create, :index]
  def index
    @drinks = Drink.all.order(name: "ASC")
  end
  def show
    @drink = Drink.find(params[:id])
  end
  def new
    @drink = Drink.new
    @drink_price = 10
  end
  def create
    @drink = Drink.new(drink_params)
    if @drink.save
      redirect_to drinks_path
    else
      render :new
    end
  end
  def edit
    @drink_price = @drink.price/100
  end
  def update
    if @drink.update(drink_params)
      redirect_to drinks_path
    else
      render :edit
    end
  end
  def destroy
    if @drink.delete
      redirect_to drinks_path
    else
      render :index
    end
  end
  private
  def set_drink
    @drink = Drink.find(params[:id])
  end
  def except_1member
    if current_member.grade == 1
      redirect_to drinks_path
    end
  end
  def drink_params
    params[:drink][:price] = params[:drink][:price].to_i*100
    params.require(:drink).permit(:name, :price, :category, :discription, :memo)
  end
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/_form.html.haml
= stylesheet_link_tag 'drinks_newEdit', media: 'all'
.drinksNewEdit
  = link_to drinks_path do
    ドリンク一覧へ戻る
  %h2.drinksNewEdit__title
    ドリンク新規登録
  = form_with model: drink, local: true, class: "drinksNewEdit__form" do |f|
    .drinksNewEdit__form__content
      %h3
        ドリンク名
      = f.text_field :name
    .drinksNewEdit__form__contents
      .drinksNewEdit__form__contents__priceCategory
        %h3
          単価
        = f.number_field :price,  {value: @drink_price, min: 10, max: 99999, style:"text-align: right"}
        00円
      .drinksNewEdit__form__contents__priceCategory
        %h3
          カテゴリー
        = f.select :category, Drink.categories.keys.to_a, prompt: "選択してください"
    .drinksNewEdit__form__content
      %h3
        メニューブック用ドリンク解説
      = f.text_area :discription
    .drinksNewEdit__form__content
      %h3
        その他メモ
      = f.text_area :memo
    .drinksNewEdit__form__submit
      = f.submit "登録"

    -# - if @drink.errors.any?
    -# %ul
    -#   - @drink.errors.full_messages.each do |m|
    -#     %li
    -#       = m

app/views/drinks/edit.html.haml
= stylesheet_link_tag 'drinks_newEdit', media: 'all'
= render partial: "form", locals: {drink: @drink}

app/views/drinks/index.html.haml
= stylesheet_link_tag 'drinks_index', media: 'all'
= javascript_include_tag 'drinks.js'
.drinksIndex
  %h2
    ドリンク一覧
  - if current_member.grade != 1
    = link_to new_drink_path, class: "drinksIndex__new" do
      新規登録
  = link_to drinks_path(format: :csv), class: "drinksIndex__csv" do
    csv出力
  = form_with id: "drinksIndex_category" do |f|
    = f.select :category, Drink.categories.keys.to_a, prompt: "全カテゴリー"
  .pageLinks
  - @drinks.each do |d|
    = link_to drink_path(d.id), class: "drink nowCategory", data: {category: d.category} do
      .drink__name
        = d.name
      .drink__price
        = "#{d.price} 円"
      .drink__show
        詳細
  .pageLinks

app/views/drinks/new.html.haml
= stylesheet_link_tag 'drinks_newEdit', media: 'all'
= render partial: "form", locals: {drink: @drink}

app/views/drinks/show.html.haml
= javascript_include_tag 'drinks.js'
= stylesheet_link_tag 'drinks_show', media: 'all'
.drinksShow
  = link_to drinks_path do
    ドリンク一覧へ戻る
  %h2.drinksShow__title
    = "#{@drink.name}の情報"
  .drinksShow__content
    %h3
      単価
    .drinksShow__content__info
      = "#{@drink.price} 円"
  .drinksShow__content
    %h3
      メニューブック用ドリンク解説
    .drinksShow__content__info
      = @drink.discription
  .drinksShow__content
    %h3
      その他メモ
    .drinksShow__content__info
      = @drink.memo
  - if current_member.grade != 1
    .drinksShow__content
      = link_to edit_drink_path(@drink.id) do
        編集
      = link_to drink_path(@drink.id), method: :delete, id: "drink_delete" do
        削除