config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  # , only: []
  resources :clients, except: :destroy
  resources :reservations, only: [:index, :create, :update] do
    member do
      put "custumDelete"
      put "revival"
      # collectionにして,jsでURLのidを抜いてdataでidを送っても可
      get "takeReservation"
    end
  end
  resources :sales
  resources :sales_drinks, only: :destroy
  # シフト機能実装後用
  # resources :myinfos, only: :index
  devise_for :members, skip: :all
  devise_scope :member do
    get '/members/sign_in' => 'devise/sessions#new', as: :new_member_session
    post '/members/sign_in' => 'devise/sessions#create', as: :member_session
    delete '/members/sign_out' => 'devise/sessions#destroy', as: :destroy_member_session
    get '/members/sign_up' => 'devise/registrations#new', as: :new_member_registration
    post '/members' => 'devise/registrations#create', as: :member_registration
  end
  resources :members, only: [:index, :edit, :update] do
    member do
      put "custumDelete"
    end
    collection do
      get "wait"
    end
  end
  root 'reservations#index'
  # シフト機能実装後用
  # root 'myinfos#index'
end

app/models/client.rb
class Client < ApplicationRecord
    validates :name, presence: true
    has_many :reservations
    def self.dates_set(clients)
        c_d = {}
        clients.each do |c|
            dates = []
            if c.reservations
                c.reservations.each do |r|
                    dates << r.date
                end
            end
            sorted_dates = dates.sort.reverse
            c_d[c.id] = sorted_dates
        end
        return c_d
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :except_1member, except: [:index, :show]
  def index
    @clients = Client.page(params[:page]).per(30).includes(:reservations)
    # 各クライアントに対する予約の日々を新しい順に並べ替えしたものとidのセット
    @clients_dates = Client.dates_set(@clients)
  end
  def show
    @client = Client.find(params[:id])
    @reservation = Reservation.where(client_id: @client.id)
  end
  def new
    @client = Client.new
  end
  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path
    else
      render :new
    end
  end
  def edit
    @client = Client.find(params[:id])
  end
  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to clients_path
    else
      render :edit
    end
  end
  # アソシエーションの問題を解決していないので削除できない
  # def destroy
  #   @client = Client.find(params[:id])
  #   @client.delete
  #   redirect_to clients_path
  # end
  private
  def except_1member
    if current_member.grade == 1
      redirect_to drinks_path
    end
  end
  def client_params
    params.require(:client).permit(:name, :memo)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
.clientsNewEdit
  = link_to clients_path do
    クライアント一覧へ戻る
  %h2.clientsNewEdit__title
    クライアント新規登録
  = form_with model: @client, local: true, class: "clientsNewEdit__form" do |f|
    .clientsNewEdit__form__content
      %h3
        お客様名
      = f.text_field :name
    .clientsNewEdit__form__content
      %h3
        お客様情報
      = f.text_area :memo
    .clientsNewEdit__form__submit
      = f.submit "保存"

  -# - if @client.errors.any?
  -# %ul
  -#   - @client.errors.full_messages.each do |m|
  -#     %li
  -#       = m

app/views/clients/edit.html.haml
= stylesheet_link_tag 'clients_newEdit', media: 'all'
= render partial: "form", locals: {client: @client}

app/views/clients/index.html.haml
= stylesheet_link_tag 'clients_index', media: 'all'
.clientsIndex
  %h2
    クライアント一覧
  - if current_member.grade != 1
    = link_to new_client_path, class: "clientsIndex__new" do
      新規登録
  = paginate @clients
  - @clients.each do |c|
    = link_to client_path(c.id), class: "client" do
      .client__content
        = c.name 
      -if @clients_dates[c.id].length > 0
        .client__content
          - @clients_dates[c.id].each do |r|
            - if r < Date.today
              = r.strftime("%Y年%m月%d日　")
            - else
              %span
                = r.strftime("%Y年%m月%d日　")
      .client__show
        詳細
  = paginate @clients

app/views/clients/new.html.haml
= stylesheet_link_tag 'clients_newEdit', media: 'all'
= render partial: "form", locals: {client: @client}

app/views/clients/show.html.haml
= javascript_include_tag 'clients.js'
= stylesheet_link_tag 'clients_show', media: 'all'
.clientsShow
  = link_to clients_path do
    クライアント一覧に戻る
  %h2.clientsShow__title
    = "#{@client.name} 様の情報"
  .clientsShow__content
    %h3
      メモ
    .clientsShow__content__info
      = @client.memo
  - if current_member.grade != 1
    .clientsShow__content
      = link_to edit_client_path(@client.id) do
        編集
      -# アソシエーションの問題を解決していないので削除できない
      -# = link_to client_path(@client.id), method: :delete, id: "client_delete" do
      -#   削除
      
  -# - @reservation.each do |r|
  -#   = link_to reservation_path(r.id) do
  -#     = r.date