config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  # , only: []
  resources :clients, except: :destroy
  resources :reservations, only: [:index, :create, :update] do
    member do
      put "custumDelete"
      put "revival"
      # collectionにして,jsでURLのidを抜いてdataでidを送っても可
      get "takeReservation"
    end
  end
  resources :sales
  resources :sales_drinks, only: :destroy
  # シフト機能実装後用
  # resources :myinfos, only: :index
  devise_for :members, skip: :all
  devise_scope :member do
    get '/members/sign_in' => 'devise/sessions#new', as: :new_member_session
    post '/members/sign_in' => 'devise/sessions#create', as: :member_session
    delete '/members/sign_out' => 'devise/sessions#destroy', as: :destroy_member_session
    get '/members/sign_up' => 'devise/registrations#new', as: :new_member_registration
    post '/members' => 'devise/registrations#create', as: :member_registration
  end
  resources :members, only: [:index, :edit, :update] do
    member do
      put "custumDelete"
    end
    collection do
      get "wait"
    end
  end
  root 'reservations#index'
  # シフト機能実装後用
  # root 'myinfos#index'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  # もともとunless: :client_id?と書いていたが、テストでうまくいかないのでこれに変更した
  validates :guest, presence: true, unless: :client
  # 以下なぜか二重にでてしまうのでコメントアウト
  # validates :room, presence: true
  # validates :kaiseki, presence: true
  validates :number_of_guest, presence: true
  validates :date, presence: true
  validates :start_hour, presence: true
  validate :opening_hour
  validates :start_minute, presence: true
  validate :four_minute
  validate :out_of_opening
  validate :booked

  belongs_to :client, optional: true
  belongs_to :kaiseki
  belongs_to :room
  belongs_to :member
  has_one :sale

  def booked
    book = false
    start_hour_up = start_hour
    start_minute_up = start_minute
    1.upto(10) do
      first = Reservation.find_by(date: date, start_hour: start_hour_up, start_minute: start_minute_up, room_id: room_id, status: [1, 2])
      if first && id != first.id
        book = true
      end
      start_minute_up+= 15
      if start_minute_up == 60
        start_minute_up = 0
        start_hour_up += 1
      end
    end
    start_hour_down = start_hour
    start_minute_down = start_minute
    1.upto(10) do
      second = Reservation.find_by(date: date, start_hour: start_hour_down, start_minute: start_minute_down, room_id: room_id, status: [1, 2])
      if second && id != second.id
        book = true
      end
      if start_minute_down == 0
        start_minute_down = 60
        start_hour_down -= 1
      end
      start_minute_down -= 15
    end
    if book
      errors.add(:date, "すでに予約があります")
    end
  end
  def opening_hour
    if start_hour < 11 || 19 < start_hour
      errors.add(:start_hour, "時間外です")
    end
  end
  def four_minute
    if !(start_minute == 0 || start_minute == 15 || start_minute == 30 || start_minute == 45)
      errors.add(:start_minute, "指定できない時間です")
    end
  end
  def out_of_opening
    if start_hour == 19 && start_minute == 45
      errors.add(:start_hour, "時間外です")
    end
  end
end

app/controllers/reservations_controller.rb
require 'date'

class ReservationsController < ApplicationController
  before_action :before_index, only: :index

  def index
    @reservations = Reservation.where(date: @selected_date).where.not(status: 0).includes(:room, :client, :sale)
    @deleted_reservations = Reservation.where(date: @selected_date, status: 0).includes(:client)
    @rooms = Room.all
    # 今日か判定してsaleへのリンクを表示
    @today = @this_date.to_date == Date.today
    @past = @this_date.to_date < Date.today
    flash[:this_date_for_new] = @this_date
    # binding.pry
    # new
    @reservation_new = Reservation.new
  end
  def takeReservation
    @reservation_show = Reservation.find(params[:id])
    if @reservation_show.client.present?
      client = @reservation_show.client.name
      clientid = @reservation_show.client.id
    else
      client = ""
      clientid = ""
    end
    if
      guest = @reservation_show.guest
    else
      guest = ""
    end
    if @reservation_show.date >= Date.today
      if @reservation_show.status == 0
        which = "revival"
      elsif @reservation_show.status != 0
        which = "custumDelete"
      end
    end
    if @reservation_show.start_minute == 0
      minute = "00"
    else
      minute = @reservation_show.start_minute
    end
    start_minute = ""
    if @reservation_show.start_minute == 0
      start_minute = "00"
    else
      start_minute = @reservation_show.start_minute
    end
    if @sale = Sale.find_by(reservation_id: @reservation_show.id)
      sale_id = @sale.id
    else
      sale_id = nil
    end
    render json: {
      id: @reservation_show.id,
      client: client,
      guest: guest,
      room: @reservation_show.room.name,
      kaiseki: @reservation_show.kaiseki.name,
      number_of_guest: @reservation_show.number_of_guest,
      date: @reservation_show.date.strftime("%Y年%m月%d日"),
      start_hour: @reservation_show.start_hour,
      start_minute: start_minute,
      memo: @reservation_show.memo,
      which: which,
      clientid: clientid,
      roomid: @reservation_show.room.id,
      kaisekiid: @reservation_show.kaiseki.id,
      minute: minute,
      status: @reservation_show.status,
      sale_id: sale_id
    }
  end
  def create
    @reservation = Reservation.new(reservation_create_params)
    if @reservation.save
      flash[:this_date] = @reservation.date
      @reservation.client.nil? ? clientGuest = @reservation.guest : clientGuest = @reservation.client.name
      respond_to do |format|
        format.json {render json: 
          {id: @reservation.id, 
          clientGuest: clientGuest,
          numOfGuest: @reservation.number_of_guest,
          memo: @reservation.memo,
          room: @reservation.room.name, 
          hour:@reservation.start_hour,
          minute:@reservation.start_minute,
          status: @reservation.status,
          sale_id: nil
          }}
        format.html {redirect_to reservations_path}
      end 
    else
      flash[:this_date].present? ? @date = flash[:this_date] : @date = Date.today + 1
      respond_to do |format|
        format.json {render json: 
          {message: @reservation.errors.full_messages, 
          }}
        # format.html {redirect_to reservations_path}
      end 
    end
  end
  # def edit
  #   @reservation = Reservation.find(params[:id])
  #   @date = @reservation.date
  #   flash[:this_date] = @reservation.date
  # end
  def update
    if params[:id].nil?
      params_id = params[:reservation][:id]
    else
      params_id = params[:id]
    end
    @reservation = Reservation.find(params_id)
    past_date = @reservation.date
    past_room_id = @reservation.room.id
    past_hour = @reservation.start_hour
    past_minute = @reservation.start_minute
    if @sale = Sale.find_by(reservation_id: @reservation.id)
      sale_id = @sale.id
    else
      sale_id = nil
    end
    if @reservation.update(reservation_update_params)
      now_date = @reservation.date
      same_date = nil
      if past_date == now_date
        same_date = 1
      end
      @reservation.client.nil? ? clientGuest = @reservation.guest : clientGuest = @reservation.client.name
      flash[:this_date] = @reservation.date
      respond_to do |format|
        format.json {render json: 
          {id: @reservation.id, 
          clientGuest: clientGuest,
          numOfGuest: @reservation.number_of_guest,
          memo: @reservation.memo,
          room: @reservation.room.name, 
          hour:@reservation.start_hour,
          minute:@reservation.start_minute,
          roomid: past_room_id,
          past_hour: past_hour,
          past_minute: past_minute,
          same_date: same_date,
          status: @reservation.status,
          sale_id: sale_id
          }}
        format.html {redirect_to reservations_path}
      end 
    else

      flash[:this_date].present? ? @date = flash[:this_date] : @date = Date.today + 1
      respond_to do |format|
        format.json {render json: 
          {message: @reservation.errors.full_messages, 
          }}
        # format.html {redirect_to reservations_path}
      end 
    end
  end
  def custumDelete
    @reservation = Reservation.find(params[:id])
    if @reservation.update!(status: 0)
      @reservation.client.nil? ? clientGuest = @reservation.guest : clientGuest = @reservation.client.name
      flash[:this_date] = @reservation.date
      respond_to do |format|
        format.json {render json: 
          {id: @reservation.id, 
          clientGuest: clientGuest,
          numOfGuest: @reservation.number_of_guest,
          roomid: @reservation.room.id, 
          hour:@reservation.start_hour,
          minute:@reservation.start_minute,
          memo: @reservation.memo
          }}
        format.html {redirect_to reservations_path}
      end 
    else
      # render :edit
    end
  end
  def revival
    @reservation = Reservation.find(params[:id])
    past_date = @reservation.date
    past_room_id = @reservation.room.id
    past_hour = @reservation.start_hour
    past_minute = @reservation.start_minute
    if @reservation.update(status: 1)
      flash[:this_date] = @reservation.date
      now_date = @reservation.date
      same_date = nil
      # 同じ日じゃなければ表には入れない
      if past_date == now_date
        same_date = 1
      end
      @reservation.client.nil? ? clientGuest = @reservation.guest : clientGuest = @reservation.client.name
      flash[:this_date] = @reservation.date
      respond_to do |format|
        format.json {render json: 
          {id: @reservation.id, 
          clientGuest: clientGuest,
          numOfGuest: @reservation.number_of_guest,
          memo: @reservation.memo,
          room: @reservation.room.name, 
          hour:@reservation.start_hour,
          minute:@reservation.start_minute,
          roomid: past_room_id,
          past_hour: past_hour,
          past_minute: past_minute,
          same_date: same_date,
          status: @reservation.status
          }}
        format.html {redirect_to reservations_path}
      end 
    else
      flash[:this_date].present? ? @date = flash[:this_date] : @date = Date.today + 1
      respond_to do |format|
        format.json {render json: 
          {id: @reservation.id,
            message: @reservation.errors.full_messages, 
          }}
        # format.html {redirect_to reservations_path}
      end 
    end
  end
  private
  def reservation_create_params
    params.require(:reservation).permit(:client_id, :guest,:room_id, :kaiseki_id, :number_of_guest, :date, :start_hour, :start_minute, :memo).merge(member_id: current_member.id, status: 1)
  end
  def reservation_update_params
    params.require(:reservation).permit(:client_id, :guest,:room_id, :kaiseki_id, :number_of_guest, :date, :start_hour, :start_minute, :memo).merge(member_id: current_member.id)
  end
  def before_index
    # createやupdate直後にはその日がflash[:this_date]に入っているのでそれ優先で表示する
    @this_date = flash[:this_date].to_time if flash[:this_date].present?
    # flash[:this_date]に値がなければindexの日指定リンクか直打ちなので分岐する
    # @this_dateは純粋な日情報
    # @selected_dateはwhereデータベース検索用
    # @dateはビュー表示用
    if @this_date.nil?
      case params['ボタン']
      when "検索" then
        @selected_date = "#{params['date(1i)']}-#{params['date(2i)']}-#{params['date(3i)']}"
        @this_date = @selected_date.to_date
        @date = "#{params['date(1i)']}年#{params['date(2i)']}月#{params['date(3i)']}日"
      when "明日" then
        @this_date = Date.today+1
      when "明後日" then
        @this_date = Date.today+2
      when "一週間後" then
        @this_date = Date.today+7
      when "前の日" then
        @this_date = params["this_date"].to_date-1
      when "次の日" then
        @this_date = params["this_date"].to_date+1
      else
        @this_date = Date.today
      end
    end
    @selected_date = @this_date.to_s if @selected_date.nil?
    @date = @this_date.strftime("%Y年%m月%d日") if @date.nil?
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.haml
= javascript_include_tag 'reservations.js'
= stylesheet_link_tag 'reservations', media: 'all'

.reservation

  -# ##########冒頭のコントローラ部################################################################
  -# ビューの配置の関係で同じform_withを3つ書いている。1つにして、position等で無理やり配置したほうがいいか検討中

  .reservation__header
    .rsvControllers
      = form_with url: reservations_path, local: true, class: "rsvControllers__submitSet1", method: :get do |f|
        != sprintf(f.date_select(:date, use_month_numbers: true,default: @this_date,date_separator: '%s'), '年 ', '月 ') +'日'
        -# != sprintf(f.date_select :date, {default: @this_date}, {class: "selects"})
        -# = f.date_select :date, {default: @this_date}, {class: "selects"}
        = f.submit "検索", name: "ボタン", class: "submits", id: "submit1"
        = f.submit "今日", class: "submits", id: "submit2"
        = f.submit "明日", name: "ボタン", class: "submits", id: "submit3"
        = f.submit "明後日", name: "ボタン", class: "submits", id: "submit4"
        = f.submit "一週間後", name: "ボタン", class: "submits", id: "submit5"
      = form_with url: reservations_path, local: true, class: "rsvControllers__submitSet2", method: :get do |f|
        = f.hidden_field :this_date, value: @this_date
        = f.submit "前の日", name: "ボタン", class: "submits", id: "submit6"
      .rsvControllers__thisDate
        = "#{@date}の予約"
      = form_with url: reservations_path, local: true, class: "rsvControllers__submitSet3", method: :get do |f|
        = f.hidden_field :this_date, value: @this_date
        = f.submit "次の日", name: "ボタン", class: "submits", id: "submit7"
      - if current_member.grade != 1
        .rsvControllers__newButton.submits#submit8
          新規予約

  -# ##########予約表###############################################################################

  .rsvTable
    .rsvTable__timeLine
      .rsvTable__timeLine__time
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          11:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          12:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          13:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          14:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          15:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          16:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          17:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          18:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          19:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          20:00
      .rsvTable__timeLine__time
        .rsvTable__timeLine__time__inner
          21:00

  -# ##########表に当てはめる予約###############################################################################

  - @reservations.each do |r|
    - status = r.status
    .reservationOne{data: {id: r.id, room: r.room.name, hour: r.start_hour, minute: r.start_minute, status: status}}
      .reservationOne__clientGuest
        - if r.client.present?
          = r.client.name+" 様"
        - else
          = r.guest+" 様"
      .reservationOne__numberOfGuest
        = r.number_of_guest.to_s+" 名"
      .reservationOne__memo
        - if r.memo.present?
          = r.memo 
      .reservationOne__showButton{data: {id: r.id}}
        詳細
      -# - if @today
      - if r.status == 1 && current_member.grade != 1 && @today
        = link_to new_sale_path(r.id), class: "reservationOne__sale" do
          未会計
      - elsif r.status == 3 && (@today || @past)
        = link_to sale_path(Sale.find_by(reservation_id: r.id)), class: "reservationOne__sale" do
          %span
            会計済
      - elsif r.status == 2 && current_member.grade != 1 && @today
        = link_to edit_sale_path(Sale.find_by(reservation_id: r.id)), class: "reservationOne__sale" do
          会計中

      -# 以下3要素デバック用あとで消す
      -# .tttttt
      -#   = r.room.name
      -# .uuuuuu
      -#   = r.start_hour
      -# .vvvvvv
      -#   = r.start_minute

-# ##########削除一覧#################################################################################

.reservationsDeleted
  %h2
    削除一覧
  - @deleted_reservations.each do |d|
    .rsvDeleted{data: {id: d.id}}
      .rsvDeleted__content
        -if d.client
          = d.client.name+" 様"
        -else
          = d.guest+" 様"
      .rsvDeleted__content
        = "#{d.number_of_guest} 名"
      .rsvDeleted__content
        = "#{d.start_hour} :"
        - if d.start_minute == 0
          = "00"
        -else
          = d.start_minute
      .rsvDeleted__content
        = d.memo
      .reservationOne__showButton.rsvDeleted__show{data: {id: d.id}}
        詳細

-# ##########新規予約スライドウインドウ####################################################################

.rsvNew.rsvNewEdit
  - if current_member.grade != 1
    = form_with model: @reservation_new, local: true, html: {class: "rsvNewEdit__form rsvNew__form", id: "reservation_new_form"} do |f|
      .rsvNew__form__left.rsvNewEdit__form__left
        %h3 お客様
        = f.select :client_id, Client.all.map{|c| [c.name, c.id]}, prompt: "クライアント"
        様
        = f.text_field :guest
        様
        %h3 日時
        != sprintf(f.date_select(:date, use_month_numbers: true,default: @this_date,date_separator: '%s'), '年 ', '月 ') +'日'
        -# = f.date_select :date, {default: @this_date}
        = f.select :start_hour, [*11..19]
        ：
        = f.select :start_minute, ['00', 15, 30, 45]
        %h3 部屋
        = f.select :room_id, Room.all.map { |r| [r.name, r.id] }, prompt: "選択してください"
        %h3 料理
        = f.select :kaiseki_id, Kaiseki.all.map { |k| [k.name, k.id] }, prompt: "選択してください"
        %h3 人数
        = f.select :number_of_guest, [*1..12], prompt: "選択してください"
      .rsvNew__form__right.rsvNewEdit__form__right
        %h3 メモ
        = f.text_area :memo
        .form_submit.rsvNewEdit__form__right__submit.rsvNewEdit__form__right__clear
          クリア
        = f.submit "登録", class: "form_submit rsvNewEdit__form__right__submit"
      .rsvNew__errorMessages.rsvNewEdit__errorMessages

-# ##########SHOWスライドウインドウ####################################################################

.rsvShow
  .rsvShow__left
    %h3 お客様
    .rsvShow__client.rsvShow__content
    .rsvShow__guest.rsvShow__content
    %h3 日時
    .rsvShow__date.rsvShow__content
    .rsvShow__start_hour.rsvShow__content
    = ":"
    .rsvShow__start_minute.rsvShow__content
    %h3 部屋
    .rsvShow__room.rsvShow__content
    %h3 料理
    .rsvShow__kaiseki.rsvShow__content
    %h3 人数
    .rsvShow__number_of_guest.rsvShow__content
    = "人"
  .rsvShow__right
    %h3 メモ
    .rsvShow__memo.rsvShow__content
  - if current_member.grade != 1
    .rsvShow__submits
      .rsvShow__edit.rsvShow__submits__submit
        編集
      .rsvShow__link.rsvShow__submits__submit
  .rsvNewEdit__errorMessages
    
-# ##########予約編集スライドウインドウ####################################################################

.rsvEdit.rsvNewEdit
  - if current_member.grade != 1
    = form_with model: @reservation_new, local: true, html: {class: "rsvNewEdit__form rsvEdit__form", id: "rsvEdit_form"} do |f|
      .rsvEdit__form__left.rsvNewEdit__form__left
        %h3 お客様
        = f.select :client_id, Client.all.map{|c| [c.name, c.id]},{}, id: "rsvEdit_client"
        様
        = f.text_field :guest, id: "rsvEdit_guest"
        様
        %h3 日時
        != sprintf(f.date_select(:date, use_month_numbers: true,default: @this_date,date_separator: '%s'), '年 ', '月 ') +'日'
        = f.select :start_hour, [*11..21],{}, id: "rsvEdit_hour"
        ：
        = f.select :start_minute, ['00', 15, 30, 45],{}, id: "rsvEdit_minute"
        %h3 部屋
        = f.select :room_id, Room.all.map { |r| [r.name, r.id] },{}, id: "rsvEdit_room"
        %h3 料理
        = f.select :kaiseki_id, Kaiseki.all.map { |k| [k.name, k.id] },{}, id: "rsvEdit_kaiseki"
        %h3 人数
        = f.select :number_of_guest, [*1..12],{}, id: "rsvEdit_number"
      .rsvEdit__form__right.rsvNewEdit__form__right
        %h3 メモ
        = f.text_area :memo, id: "rsvEdit_memo"
        = f.submit "登録", class: "form_submit rsvNewEdit__form__right__submit"
      .rsvEdit__errorMessages.rsvNewEdit__errorMessages

-# ##########roomデータ送信用hidden####################################################################

- @rooms.each do |r|
  .data--room{data: {name: r.name, id: r.id}}
#current_member_info{data: {grade: current_member.grade}}
- @today ? today = 1 : today = 0
- @past ? past = 1 : past = 0
#date_info{data: {today: today, past: past}}