config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  # , only: []
  resources :clients, except: :destroy
  resources :reservations, only: [:index, :create, :update] do
    member do
      put "custumDelete"
      put "revival"
      # collectionにして,jsでURLのidを抜いてdataでidを送っても可
      get "takeReservation"
    end
  end
  resources :sales
  resources :sales_drinks, only: :destroy
  # シフト機能実装後用
  # resources :myinfos, only: :index
  devise_for :members, skip: :all
  devise_scope :member do
    get '/members/sign_in' => 'devise/sessions#new', as: :new_member_session
    post '/members/sign_in' => 'devise/sessions#create', as: :member_session
    delete '/members/sign_out' => 'devise/sessions#destroy', as: :destroy_member_session
    get '/members/sign_up' => 'devise/registrations#new', as: :new_member_registration
    post '/members' => 'devise/registrations#create', as: :member_registration
  end
  resources :members, only: [:index, :edit, :update] do
    member do
      put "custumDelete"
    end
    collection do
      get "wait"
    end
  end
  root 'reservations#index'
  # シフト機能実装後用
  # root 'myinfos#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width,initial-scale=1.0,minimum-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ryotei
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = javascript_include_tag "header.js"
    = stylesheet_link_tag 'reset', media: 'all'
    = stylesheet_link_tag "application", media: "all"

    %header.header
      - if member_signed_in?
        - if current_member.grade == nil
          .header__signinLogin
            = link_to "ログイン画面へ", destroy_member_session_path, method: :delete, class: "header__signinLogin__link header__signinLogin__link__now"
        - else
          .header__nav
            .header__nav__menu
              Menu
            %ul.header__nav__hover
              -# シフト機能実装後用
              -# %li.header__nav__hover__li
              -#   = link_to root_path do
              -#     TOP
              %li.header__nav__hover__li
                = link_to reservations_path do
                  予約
              %li.header__nav__hover__li
                = link_to clients_path do
                  クライアント
              %li.header__nav__hover__li
                = link_to members_path do
                  メンバー
              %li.header__nav__hover__li
                = link_to drinks_path do
                  ドリンク
          .header__account
            .header__account__clock
            %ul.header__account__hover
              
              %li.header__account__hover__li
                = current_member.name
              %li.header__account__hover__li
                = link_to "ログアウト", destroy_member_session_path, method: :delete, class: "header__name__logout"
      
      - elsif request.path == new_member_session_path
        .header__signinLogin
          = link_to "ログイン", new_member_session_path, class: "header__signinLogin__link header__signinLogin__link__now"
          = link_to "会員登録", new_member_registration_path, class: "header__signinLogin__link"
      - elsif request.path == new_member_registration_path
        .header__signinLogin
          = link_to "ログイン", new_member_session_path, class: "header__signinLogin__link"
          = link_to "会員登録", new_member_registration_path, class: "header__signinLogin__link header__signinLogin__link__now"
    = yield